dist: trusty
sudo: required
group: edge
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#          packages:
#            - clang-3.7
#      env: COMPILER=clang++-3.7
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev
 - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - sudo tar xf release-1.7.0.tar.gz
 - cd googletest-release-1.7.0
# - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo ./make/make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"
 - chmod +x PortableUnitTestsDriver.sh
script: ./PortableUnitTestsDriver.sh
notifications:
  email:
    recipients:
      - ci@opentrv.uk
    on_success: change
    on_failure: always
  irc:
    channels: "irc.z.je#opentrv"
    on_success: change
    on_failure: change
  

